### ISSUE TITLE
Improve texts in home screen cards

### ISSUE THREAD

**Issue by pdandradeb** [appjusto/app#109]
![Screenshot_20210525-154746.png](https://user-images.githubusercontent.com/30743/119552004-9fce0d00-bd70-11eb-9bea-3a14297087c4.png)

**Comment by pdandradeb** [comment]
Be more descriptive on the top card
Fix long addresses

**Comment by danielfbl** [comment]
fixed long strings problem and added more titles and details to be more descriptive about what is happening at a given stage in an order
